project_id = "voppamtbdqchaopwtlkc"

[functions.analyze-indicators]
verify_jwt = false

[functions.transcribe-audio]
verify_jwt = false

[functions.whatsapp-webhook]
verify_jwt = false

[functions.ai-response-dispatcher]
verify_jwt = false
